name: iot_app
description: Smart Lamp IoT App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^19.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # TAMBAHKAN BARIS DI BAWAH INI
  assets:
    - assets/bg.jpeg
